### ISSUE TITLE
Nie pokazuj tego w testach

### ISSUE THREAD

**Issue by xKoem** [JaroslawSlaby/OXTheGame#57]
T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@51cdd8a
Enter 1st player name: 
Choose sign (O/X) for player O
Enter 2nd player name: 
Enter 1st player name: 
Choose sign (O/X) for player X
Enter 2nd player name: 
y\x	0		1		2		3		4	
0 |		||	X	||		||		||		|
1 |		||		||	X	||		||		|
2 |		||		||		||	O	||		|
3 |		||		||		||		||	X	|
4 |		||		||		||		||		|
Tests run: 59, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.355 sec

**Comment by JaroslawZaczyk** [comment]
gotowe
